'use client';

import React from 'react';

interface ModelBadgeProps {
    modelUsed?: string;
    displayName?: string;
    ragFallback?: string;
}

// Map internal model IDs to icons
const MODEL_ICONS: Record<string, string> = {
    'llama-3.1-8b-instant': '⚡',
    'llama-3.3-70b-versatile': '🦙',
    'openai/gpt-oss-120b': '🧠',
    'openai/gpt-oss-20b': '✨',
    'mixtral-8x7b-32768': '🌀',
};

export default function ModelBadge({ modelUsed, displayName, ragFallback }: ModelBadgeProps) {
    if (!modelUsed && !ragFallback) return null;

    const icon = modelUsed ? (MODEL_ICONS[modelUsed] ?? '🤖') : null;
    const label = displayName ?? modelUsed ?? '';

    return (
        <div className="flex items-center gap-2 flex-wrap mt-2 mb-1">
            {modelUsed && (
                <span
                    className="model-badge"
                    title={`Generated by: ${modelUsed}`}
                >
                    {icon} {label}
                </span>
            )}
            {ragFallback && (
                <span className="rag-fallback-badge" title={ragFallback}>
                    🔀 PDF fallback → Web
                </span>
            )}
        </div>
    );
}
